### ISSUE TITLE
[FEATURE] New CS Modifications

### ISSUE THREAD

**Issue by Siryphas** [witchertrpg-foundryvtt/TheWitcherTRPG#146]
**Is your feature request related to a problem? Please describe.**
The new character sheet features don't allow manual input for things like Shield are no longer able to be edited manually, making it difficult to adjust for players.

**Describe the solution you'd like**
Manual Modification of all CS options

**Comment by Stexinator** [comment]
@moliloo

**Comment by moliloo** [comment]
The only inputs i remove is Shield, Luck and Adrenaline

Remove the input from Shield because i see a automatation in Qen, so i think is dont need a input for it

Luck and Adrenaline its because i switch the input from buttons

I can put a input in all of this three if you want, but i will need to remove the buttons wich increase and reset the values

**Comment by Siryphas** [comment]
All of those have reasons for manual input. 
First of all, Shield can be used to automate the Cover mechanics. Also, Quen only lasts for 10 rounds, and if the PCs finish a combat and still have Quen active, I can't remove their shield without having to damage them and then give them HP back.
Second, Luck doesn't allow modifiers to apply to the number of Luck points. If a PC has a Lucky item from their lifepath, or some other such item that adds more Luck than their base statistic allows for, we have to count it manually.
Third, while I haven't used Adrenaline much, I know there are some Runes that give extra Adrenaline and reduce the STA cost of using Adrenaline. So being able to manually adjust it is important.
