### ISSUE TITLE
Athletics double dipping in global modifiers

### ISSUE THREAD

**Issue by joridin** [witchertrpg-foundryvtt/TheWitcherTRPG#46]
Athletics seems to be included in the definition of both Melee and Ranged skills in global modifiers, this any modifier that affects both effectively applies twice the bonus or penalty to Athletics.

**Comment by Stexinator** [comment]
This can only be fixed with creating a new skill group.

Can you describ your use case in more detail?

**Comment by joridin** [comment]
teah so say i need a modifier that affects attack and defense rolls, so i
select both melee and ramged skills to get -1. since athletics is included
under both unbrellas, it's going to be affected by -1 twice.

i would think the simple solution would be to remove athletics from the
melee skills group

**Comment by Stexinator** [comment]
Well, I cannot find why Athletics was in melee in the first place. @Siryphas I think you are the person that I know that knows the rule best. Any objections?

**Comment by Siryphas** [comment]
Of the top of my head, I can't think of why Athletics would be used in Melee. It's generally only used for Thrown Weapon Attacks, and as a Reposition Defense.

I agree their for "Attacks and Defense," since there are quite a few conditions that affect both. It could also just cover each associated Skill once, (since Athletics is an attack and defense) which would solve this problem.
