### ISSUE TITLE
Make it easier to convert

### ISSUE THREAD

**Issue by LinkDragmire** [witchertrpg-foundryvtt/TheWitcherTRPG#56]
When converting from the old system (v0.9.7) most items are not handled correctly. Weapon skills have to be redone and nearly every actor has to be adjusted. This makes it really hard to update, when you got a filled world with all assets.

It would be the biggest held, when the information is handed over while updating. Maybe there are some points that have to be adjusted, due to new mechanism used, but there are several things, which are just dropped.

Maybe this is correlating with missing localization. I'm using the system in german and some parts in the new system seem to be missing a translation.

**Comment by Stexinator** [comment]
I tried to add migration several times when working on my fork. But the old data model was quite incomplete, had several errors and didnt allow migrations. Unfortunately all data that was changed before I migrated to ``dataModels`` were incompletly migrated. Due to it happening in the span of nearly a year I didnt seemed it as necessary.

With the new data models migration should be possible now, due to foundry keeping the old data. But I dont know what the problems might be now. If you can give me a detailed write up I see what I can do.

Weapon skills need to be done by hand again, unfortunately there is no way around, due to prior mishandling of the skills.

>Maybe this is correlating with missing localization. I'm using the system in german and some parts in the new system seem to be missing a translation.

I only have the english books so I did not care for the german translations. Also beware that there are several errors in the german books and as far as I know they did not get an errata. @ortegamarcel wanted to create an issue to bring the german translations up to speed, if you want you can support us with that :)

**Comment by LinkDragmire** [comment]
Ok, i get that. Weapon skills were one of the main points.

I don't got much time, but I would like to partizipate in the translation, when I'm available.
